name: huggingface_ds6
channels:
  - conda-forge
  - plotly
dependencies:
  - python
  - jupyter
  - pandas
  - pytorch
  - torchvision
  - matplotlib
  - accelerate
  - seaborn
  - scikit-learn
  - scipy
  - plotly
  - umap-learn
  - pip
  - pip:
    - "transformers[sentencepiece]"
    - datasets
    - evaluate
    - streamlit
    - watchdog
    #- --upgrade accelerate
